// CreatePostModal.tsx
//
// This file defines the CreatePostModal component, which provides a modal dialog for creating a new social media post.
// The modal includes form controls for selecting post type, platforms, writing a description, viewing trends, uploading or generating images, and receiving AI suggestions.
// It also supports scheduling posts and displays a success notification upon completion.
//
// The component leverages custom hooks and modular subcomponents for a clean, maintainable structure.

import { useState, useEffect } from "react";
import { Loader } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/shared/components/ui/dialog";
import { Button } from "@/shared/components/ui/button";
import { Label } from "@/shared/components/ui/label";

import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/shared/components/ui/select";
import { ScrollArea } from "@/shared/components/ui/scroll-area";

import { usePost } from "../hooks/usePost";
import { POST_TYPES, PostType } from "../types/createPostTypes";
import { PlatformSelector } from "./PlatformSelector";

import { TrendsSection } from "./TrendsSection";
import { ImageUpload } from "./ImageUpload";
import { AISuggestion } from "./AISuggestion";
import { ScheduleModal } from "@/shared/components/ScheduleModal";
import { SuccessNotification } from "./SuccessNotification";

import { cn } from "@/shared/utils/utils";
import { useAppSelector, RootState } from "@/core/store/store";


/**
 * Props for CreatePostModal
 * @property {boolean} isOpen - Controls whether the modal is open.
 * @property {() => void} onClose - Callback to close the modal.
 */
interface CreatePostModalProps {
  isOpen: boolean;
  onClose: () => void;
}

/**
 * CreatePostModal
 *
 * This component renders a modal dialog for creating a new post. It includes:
 * - Post type selection
 * - Platform selection
 * - Description input with AI suggestion
 * - Trends and hashtag suggestions
 * - Image upload/generation
 * - AI posting suggestion
 * - Scheduling functionality
 * - Success notification
 *
 * State and actions are managed via the usePost custom hook.
 */
export function CreatePostModal({ isOpen, onClose }: CreatePostModalProps) {
  // Local state for company dropdown
  const [companies, setCompanies] = useState<
    Array<{ name: string; url: string }>
  >([]);
  const [selectedCompany, setSelectedCompany] = useState<string>("");

  // Fetch companies list from API when modal opens
  useEffect(() => {
    if (isOpen) {
      fetch("https://n8n.sofiatechnology.ai/webhook/brands-list")
        .then((response) => {
          if (!response.ok) {
            throw new Error(`HTTP error! status: ${response.status}`);
          }
          return response.text();
        })
        .then((text) => {
          if (!text || text.trim() === "") {
            console.warn("Empty response from brands API");
            setCompanies([]);
            return;
          }
          const data = JSON.parse(text);
          setCompanies(data.brands || []);
        })
        .catch((error) => {
          console.error("Failed to load companies:", error);
          setCompanies([]);
        });
    }
  }, [isOpen]);

  // Get the URL of the selected company
  const selectedCompanyUrl = companies.find(
    (c) => c.name === selectedCompany,
  )?.url;

  // usePost hook provides all state, actions, and validators for the post creation flow
  const {
    // State
    postType, // Current selected post type

    description, // Post description text
    hasImage, // Boolean indicating if an image is present
    generatedImage, // Image generated by AI
    uploadedImages, // Imágenes subidas por el usuario
    scheduledDate, // Date selected for scheduling
    scheduledTime, // Time selected for scheduling
    trends, // Trending hashtags/topics
    loadingImage, // Loading state for image generation/upload
    loadingSubmit, // Loading state for post submission
    loadingSchedule, // Loading state for scheduling
    loadingTrends, // Loading state for trends
    showSuccess, // Boolean to show success notification
    showScheduleModal, // Boolean to show schedule modal
    fileInputRef, // Ref for file input element
    // Actions
    handlePostTypeChange, // Change post type
    handleAddHashtag, // Add hashtag from trends
    handleImageGeneration, // Generate image with AI
    handleFileUpload, // Upload image file
    handleRemoveImage, // Remove image
    handleRemoveUploadedImage, // Eliminar imagen subida
    handleSubmit, // Submit post
    handleSchedule, // Confirm scheduling
    // Setters
    setScheduledDate, // Set scheduled date
    setScheduledTime, // Set scheduled time
    setShowScheduleModal, // Show/hide schedule modal
    // Validators
    isFormValid, // Validate form for submission
    isScheduleValid, // Validate schedule fields
  } = usePost(selectedCompanyUrl);

  const { selectedPlatforms } = useAppSelector(
    (state: RootState) => state.createPost,
  );

  // Determines if AI suggestion can be requested (requires post type and at least one platform)
  const canSuggest = !!postType && selectedPlatforms.length > 0;
  // Determines if image can be generated (requires canSuggest and non-empty description)
  const canGenerateImage = canSuggest && !!description.trim();

  return (
    <>
      {/* Main dialog for creating a post */}
      <Dialog open={isOpen} onOpenChange={onClose}>
        <DialogContent className="max-w-[90vw] w-full h-fit max-h-fit">
          {/* Success notification shown after post creation */}
          <SuccessNotification show={showSuccess} />
          <DialogHeader>
            <DialogTitle className="text-gray-900">Create New Post</DialogTitle>
          </DialogHeader>
          {/* Scrollable area for form fields */}
          <ScrollArea className="min-lg:h-[70svh] max-lg:h-[50svh] max-h-[80svh] w-full">
            <div className="flex flex-col justify-between items-start gap-4">
              <div className="flex justify-start items-center gap-4">
                {/* Platform Selection (e.g., Facebook, Twitter) */}
                <PlatformSelector />
              </div>
              <div className="space-y-6 text-gray-900">
                {/* Post Type Selection */}
                <div className="space-y-2 flex gap-3 items-center">
                  <Label htmlFor="post-type">Post Type</Label>
                  <div className="flex gap-2">
                    {/* Render available post types */}
                    {POST_TYPES.map((type) => (
                      <Button
                        key={type.value}
                        className={cn("text-xs")}
                        variant={
                          postType === type.value ? "secondary" : "outline"
                        }
                        onClick={() =>
                          handlePostTypeChange(type.value as PostType)
                        }
                      >
                        {type.label}
                      </Button>
                    ))}
                  </div>
                  {/* Brand DNA Toggle - positioned next to Post Type */}
                  {/* <div className="flex items-center space-x-2 pt-2">
                  <Checkbox
                    id="use-brand-dna"
                    checked={useBrandDna}
                    onCheckedChange={handleToggleUseBrandDna}
                  />
                  <Label
                    htmlFor="use-brand-dna"
                    className="cursor-pointer text-sm font-medium"
                  >
                    Use Brand DNA
                  </Label>
                  <TooltipHover
                    title="Brand DNA"
                    content="Applies your extracted brand tone, colors, and typography to this post."
                    side="right"
                  >
                    <Info className="w-4 h-4 text-gray-500 hover:text-gray-700 cursor-help" />
                  </TooltipHover>
                </div> */}
                </div>

                {/* Company Selection - Only shown when Use Brand DNA is checked */}

                <div className="space-y-2">
                  <Label htmlFor="company">Select Company *</Label>
                  <Select
                    value={selectedCompany}
                    onValueChange={(value) => setSelectedCompany(value)}
                  >
                    <SelectTrigger id="company">
                      <SelectValue placeholder="Choose a company" />
                    </SelectTrigger>
                    <SelectContent>
                      {companies.map((company) => (
                        <SelectItem key={company.name} value={company.name}>
                          {company.name}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <AISuggestion />
                <div className="flex w-full flex-col relative gap-3 m-0 p-2 border border-outline rounded-md">
                  {/* <div className="flex flex-row justify-start items-start gap-0">
                  <CopyTextGeneration />
                  <CreateImageGeneration />

                  <Button variant={"outline"} className="rounded-none border">
                    <PackageOpen />
                    Choose image from library
                  </Button>
                  <Button
                    variant={"outline"}
                    className="rounded-none rounded-r-md"
                  >
                    <Hash />
                    Include hastag trends
                  </Button>
                </div>
                <DescriptionInput
                  description={description}
                  onDescriptionChange={handleDescriptionChange}
                  loadingSuggestion={loadingSuggestion}
                /> */}
                  <TrendsSection
                    trends={trends}
                    loadingTrends={loadingTrends}
                    onAddHashtag={handleAddHashtag}
                  />
                </div>
                {/* <PostFeedback errors={validationErrors} /> */}

                {/* Image Upload and AI Generation */}
                <ImageUpload
                  hasImage={hasImage}
                  generatedImage={generatedImage}
                  uploadedImages={uploadedImages}
                  loadingImage={loadingImage}
                  fileInputRef={fileInputRef}
                  onImageGeneration={handleImageGeneration}
                  onFileUpload={handleFileUpload}
                  onRemoveImage={handleRemoveImage}
                  onRemoveUploadedImage={handleRemoveUploadedImage}
                  canGenerateImage={canGenerateImage}
                />

                {/* AI Suggestion for optimal posting time and strategy */}
              </div>
            </div>
          </ScrollArea>

          {/* Action Buttons: Cancel, Schedule, Create Post */}
          <div className="flex justify-end space-x-3 pt-4 border-t">
            <Button variant="error" onClick={onClose}>
              Cancel
            </Button>
            <Button
              onClick={() => setShowScheduleModal(true)}
              disabled={!isFormValid() || loadingSubmit}
              variant="secondary"
            >
              Schedule
            </Button>
            <Button
              onClick={handleSubmit}
              disabled={!isFormValid() || loadingSubmit}
            >
              {/* Show loading spinner when submitting */}
              {loadingSubmit ? (
                <Loader className="animate-spin w-4 h-4 mr-2 text-green-600" />
              ) : null}
              Create Post
            </Button>
          </div>
        </DialogContent>
      </Dialog>

      {/* Schedule Modal for selecting date and time */}
      <ScheduleModal
        isOpen={showScheduleModal}
        onClose={() => setShowScheduleModal(false)}
        scheduledDate={scheduledDate}
        scheduledTime={scheduledTime}
        loadingSchedule={loadingSchedule}
        onDateChange={setScheduledDate}
        onTimeChange={setScheduledTime}
        onConfirm={handleSchedule}
        isValid={!!isScheduleValid()}
      />
    </>
  );
}
// End of CreatePostModal.tsx
