// CreatePostModal.tsx
//
// This file defines the CreatePostModal component, which provides a modal dialog for creating a new social media post.
// The modal includes form controls for selecting post type, platforms, writing a description, viewing trends, uploading or generating images, and receiving AI suggestions.
// It also supports scheduling posts and displays a success notification upon completion.
//
// The component leverages custom hooks and modular subcomponents for a clean, maintainable structure.

import { Loader } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/shared/components/ui/dialog";
import { Button } from "@/shared/components/ui/button";
import { Label } from "@/shared/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/shared/components/ui/select";
import { ScrollArea } from "@/shared/components/ui/scroll-area";

import { usePost } from '../hooks/usePost';
import { POST_TYPES } from '../types/createPostTypes';
import { PlatformSelector } from './PlatformSelector';
import { DescriptionInput } from './DescriptionInput';
import { TrendsSection } from './TrendsSection';
import { ImageUpload } from './ImageUpload';
import { AISuggestion } from './AISuggestion';
import { ScheduleModal } from '../../../shared/components/ScheduleModal';
import { SuccessNotification } from './SuccessNotification';

/**
 * Props for CreatePostModal
 * @property {boolean} isOpen - Controls whether the modal is open.
 * @property {() => void} onClose - Callback to close the modal.
 */
interface CreatePostModalProps {
  isOpen: boolean;
  onClose: () => void;
}

/**
 * CreatePostModal
 *
 * This component renders a modal dialog for creating a new post. It includes:
 * - Post type selection
 * - Platform selection
 * - Description input with AI suggestion
 * - Trends and hashtag suggestions
 * - Image upload/generation
 * - AI posting suggestion
 * - Scheduling functionality
 * - Success notification
 *
 * State and actions are managed via the usePost custom hook.
 */
export function CreatePostModal({ isOpen, onClose }: CreatePostModalProps) {
  // usePost hook provides all state, actions, and validators for the post creation flow
  const {
    // State
    postType, // Current selected post type
    selectedPlatforms, // Array of selected platforms
    description, // Post description text
    hasImage, // Boolean indicating if an image is present
    generatedImage, // Image generated by AI
    uploadedImages, // Imágenes subidas por el usuario
    scheduledDate, // Date selected for scheduling
    scheduledTime, // Time selected for scheduling
    trends, // Trending hashtags/topics
    loadingSuggestion, // Loading state for AI suggestion
    loadingImage, // Loading state for image generation/upload
    loadingSubmit, // Loading state for post submission
    loadingSchedule, // Loading state for scheduling
    loadingTrends, // Loading state for trends
    showSuccess, // Boolean to show success notification
    showScheduleModal, // Boolean to show schedule modal
    fileInputRef, // Ref for file input element
    
    // Actions
    handlePostTypeChange, // Change post type
    handlePlatformToggle, // Toggle platform selection
    handleDescriptionChange, // Change description
    handleAddHashtag, // Add hashtag from trends
    handleSuggestion, // Trigger AI suggestion
    handleImageGeneration, // Generate image with AI
    handleFileUpload, // Upload image file
    handleRemoveImage, // Remove image
    handleRemoveUploadedImage, // Eliminar imagen subida
    handleSubmit, // Submit post
    handleSchedule, // Confirm scheduling
    
    // Setters
    setScheduledDate, // Set scheduled date
    setScheduledTime, // Set scheduled time
    setShowScheduleModal, // Show/hide schedule modal
    
    // Validators
    isFormValid, // Validate form for submission
    isScheduleValid, // Validate schedule fields
  } = usePost();

  // Determines if AI suggestion can be requested (requires post type and at least one platform)
  const canSuggest = !!postType && selectedPlatforms.length > 0;
  // Determines if image can be generated (requires canSuggest and non-empty description)
  const canGenerateImage = canSuggest && !!description.trim();

  return (
    <>
      {/* Main dialog for creating a post */}
      <Dialog open={isOpen} onOpenChange={onClose}>
        <DialogContent className="max-w-2xl">
          {/* Success notification shown after post creation */}
          <SuccessNotification show={showSuccess} />
          
          <DialogHeader>
            <DialogTitle className="text-gray-900">Create New Post</DialogTitle>
          </DialogHeader>

          {/* Scrollable area for form fields */}
          <ScrollArea className="max-h-[70vh] pr-2">
            <div className="space-y-6 text-gray-900">
              {/* Post Type Selection */}
              <div className="space-y-2">
                <Label htmlFor="post-type">Post Type</Label>
                <Select value={postType} onValueChange={handlePostTypeChange}>
                  <SelectTrigger>
                    <SelectValue placeholder="Select post type" />
                  </SelectTrigger>
                  <SelectContent>
                    {/* Render available post types */}
                    {POST_TYPES.map((type) => (
                      <SelectItem key={type.value} value={type.value}>
                        {type.label}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              {/* Platform Selection (e.g., Facebook, Twitter) */}
              <PlatformSelector
                selectedPlatforms={selectedPlatforms}
                onTogglePlatform={handlePlatformToggle}
              />

              {/* Post Description with AI Suggestion button */}
              <DescriptionInput
                description={description}
                onDescriptionChange={handleDescriptionChange}
                onSuggestion={handleSuggestion}
                loadingSuggestion={loadingSuggestion}
                canSuggest={canSuggest}
              />

              {/* Trends and Hashtag Suggestions */}
              <TrendsSection
                selectedPlatforms={selectedPlatforms}
                trends={trends}
                loadingTrends={loadingTrends}
                onAddHashtag={handleAddHashtag}
              />

              {/* Image Upload and AI Generation */}
              <ImageUpload
                hasImage={hasImage}
                generatedImage={generatedImage}
                uploadedImages={uploadedImages}
                loadingImage={loadingImage}
                fileInputRef={fileInputRef}
                onImageGeneration={handleImageGeneration}
                onFileUpload={handleFileUpload}
                onRemoveImage={handleRemoveImage}
                onRemoveUploadedImage={handleRemoveUploadedImage}
                canGenerateImage={canGenerateImage}
              />

              {/* AI Suggestion for optimal posting time and strategy */}
              <AISuggestion />
            </div>
          </ScrollArea>

          {/* Action Buttons: Cancel, Schedule, Create Post */}
          <div className="flex justify-end space-x-3 pt-4 border-t">
            <Button
              className="bg-red-500 text-white"
              variant="outline"
              onClick={onClose}
            >
              Cancel
            </Button>
            <Button
              onClick={() => setShowScheduleModal(true)}
              disabled={!isFormValid() || loadingSubmit}
              className="bg-blue-600 text-white"
            >
              Schedule
            </Button>
            <Button
              onClick={handleSubmit}
              disabled={!isFormValid() || loadingSubmit}
            >
              {/* Show loading spinner when submitting */}
              {loadingSubmit ? (
                <Loader className="animate-spin w-4 h-4 mr-2 text-green-600" />
              ) : null}
              Create Post
            </Button>
          </div>
        </DialogContent>
      </Dialog>

      {/* Schedule Modal for selecting date and time */}
      <ScheduleModal
        isOpen={showScheduleModal}
        onClose={() => setShowScheduleModal(false)}
        scheduledDate={scheduledDate}
        scheduledTime={scheduledTime}
        loadingSchedule={loadingSchedule}
        onDateChange={setScheduledDate}
        onTimeChange={setScheduledTime}
        onConfirm={handleSchedule}
        isValid={!!isScheduleValid()}
      />
    </>
  );
}
// End of CreatePostModal.tsx
