export type Country = {
  title: string;
  value: string;
  flag: string;
};



export const COUNTRIES: Country[] = [
  { title: "Afghanistan", value: "AF", flag: "🇦🇫" },
  { title: "Albania", value: "AL", flag: "🇦🇱" },
  { title: "Algeria", value: "DZ", flag: "🇩🇿" },
  { title: "Andorra", value: "AD", flag: "🇦🇩" },
  { title: "Angola", value: "AO", flag: "🇦🇴" },
  { title: "Antigua and Barbuda", value: "AG", flag: "🇦🇬" },
  { title: "Argentina", value: "AR", flag: "🇦🇷" },
  { title: "Armenia", value: "AM", flag: "🇦🇲" },
  { title: "Australia", value: "AU", flag: "🇦🇺" },
  { title: "Austria", value: "AT", flag: "🇦🇹" },
  { title: "Azerbaijan", value: "AZ", flag: "🇦🇿" },
  { title: "Bahamas", value: "BS", flag: "🇧🇸" },
  { title: "Bahrain", value: "BH", flag: "🇧🇭" },
  { title: "Bangladesh", value: "BD", flag: "🇧🇩" },
  { title: "Barbados", value: "BB", flag: "🇧🇧" },
  { title: "Belarus", value: "BY", flag: "🇧🇾" },
  { title: "Belgium", value: "BE", flag: "🇧🇪" },
  { title: "Belize", value: "BZ", flag: "🇧🇿" },
  { title: "Benin", value: "BJ", flag: "🇧🇯" },
  { title: "Bhutan", value: "BT", flag: "🇧🇹" },
  { title: "Bolivia", value: "BO", flag: "🇧🇴" },
  { title: "Bosnia and Herzegovina", value: "BA", flag: "🇧🇦" },
  { title: "Botswana", value: "BW", flag: "🇧🇼" },
  { title: "Brazil", value: "BR", flag: "🇧🇷" },
  { title: "Brunei", value: "BN", flag: "🇧🇳" },
  { title: "Bulgaria", value: "BG", flag: "🇧🇬" },
  { title: "Burkina Faso", value: "BF", flag: "🇧🇫" },
  { title: "Burundi", value: "BI", flag: "🇧🇮" },
  { title: "Cambodia", value: "KH", flag: "🇰🇭" },
  { title: "Cameroon", value: "CM", flag: "🇨🇲" },
  { title: "Canada", value: "CA", flag: "🇨🇦" },
  { title: "Cape Verde", value: "CV", flag: "🇨🇻" },
  { title: "Central African Republic", value: "CF", flag: "🇨🇫" },
  { title: "Chad", value: "TD", flag: "🇹🇩" },
  { title: "Chile", value: "CL", flag: "🇨🇱" },
  { title: "China", value: "CN", flag: "🇨🇳" },
  { title: "Colombia", value: "CO", flag: "🇨🇴" },
  { title: "Comoros", value: "KM", flag: "🇰🇲" },
  { title: "Congo", value: "CG", flag: "🇨🇬" },
  { title: "Costa Rica", value: "CR", flag: "🇨🇷" },
  { title: "Croatia", value: "HR", flag: "🇭🇷" },
  { title: "Cuba", value: "CU", flag: "🇨🇺" },
  { title: "Cyprus", value: "CY", flag: "🇨🇾" },
  { title: "Czech Republic", value: "CZ", flag: "🇨🇿" },
  { title: "Denmark", value: "DK", flag: "🇩🇰" },
  { title: "Djibouti", value: "DJ", flag: "🇩🇯" },
  { title: "Dominica", value: "DM", flag: "🇩🇲" },
  { title: "Dominican Republic", value: "DO", flag: "🇩🇴" },
  { title: "East Timor", value: "TL", flag: "🇹🇱" },
  { title: "Ecuador", value: "EC", flag: "🇪🇨" },
  { title: "Egypt", value: "EG", flag: "🇪🇬" },
  { title: "El Salvador", value: "SV", flag: "🇸🇻" },
  { title: "Equatorial Guinea", value: "GQ", flag: "🇬🇶" },
  { title: "Eritrea", value: "ER", flag: "🇪🇷" },
  { title: "Estonia", value: "EE", flag: "🇪🇪" },
  { title: "Ethiopia", value: "ET", flag: "🇪🇹" },
  { title: "Fiji", value: "FJ", flag: "🇫🇯" },
  { title: "Finland", value: "FI", flag: "🇫🇮" },
  { title: "France", value: "FR", flag: "🇫🇷" },
  { title: "Gabon", value: "GA", flag: "🇬🇦" },
  { title: "Gambia", value: "GM", flag: "🇬🇲" },
  { title: "Georgia", value: "GE", flag: "🇬🇪" },
  { title: "Germany", value: "DE", flag: "🇩🇪" },
  { title: "Ghana", value: "GH", flag: "🇬🇭" },
  { title: "Greece", value: "GR", flag: "🇬🇷" },
  { title: "Grenada", value: "GD", flag: "🇬🇩" },
  { title: "Guatemala", value: "GT", flag: "🇬🇹" },
  { title: "Guinea", value: "GN", flag: "🇬🇳" },
  { title: "Guinea-Bissau", value: "GW", flag: "🇬🇼" },
  { title: "Guyana", value: "GY", flag: "🇬🇾" },
  { title: "Haiti", value: "HT", flag: "🇭🇹" },
  { title: "Honduras", value: "HN", flag: "🇭🇳" },
  { title: "Hungary", value: "HU", flag: "🇭🇺" },
  { title: "Iceland", value: "IS", flag: "🇮🇸" },
  { title: "India", value: "IN", flag: "🇮🇳" },
  { title: "Indonesia", value: "ID", flag: "🇮🇩" },
  { title: "Iran", value: "IR", flag: "🇮🇷" },
  { title: "Iraq", value: "IQ", flag: "🇮🇶" },
  { title: "Ireland", value: "IE", flag: "🇮🇪" },
  { title: "Israel", value: "IL", flag: "🇮🇱" },
  { title: "Italy", value: "IT", flag: "🇮🇹" },
  { title: "Jamaica", value: "JM", flag: "🇯🇲" },
  { title: "Japan", value: "JP", flag: "🇯🇵" },
  { title: "Jordan", value: "JO", flag: "🇯🇴" },
  { title: "Kazakhstan", value: "KZ", flag: "🇰🇿" },
  { title: "Kenya", value: "KE", flag: "🇰🇪" },
  { title: "Kiribati", value: "KI", flag: "🇰🇮" },
  { title: "North Korea", value: "KP", flag: "🇰🇵" },
  { title: "South Korea", value: "KR", flag: "🇰🇷" },
  { title: "Kuwait", value: "KW", flag: "🇰🇼" },
  { title: "Kyrgyzstan", value: "KG", flag: "🇰🇬" },
  { title: "Laos", value: "LA", flag: "🇱🇦" },
  { title: "Latvia", value: "LV", flag: "🇱🇻" },
  { title: "Lebanon", value: "LB", flag: "🇱🇧" },
  { title: "Lesotho", value: "LS", flag: "🇱🇸" },
  { title: "Liberia", value: "LR", flag: "🇱🇷" },
  { title: "Libya", value: "LY", flag: "🇱🇾" },
  { title: "Liechtenstein", value: "LI", flag: "🇱🇮" },
  { title: "Lithuania", value: "LT", flag: "🇱🇹" },
  { title: "Luxembourg", value: "LU", flag: "🇱🇺" },
  { title: "Madagascar", value: "MG", flag: "🇲🇬" },
  { title: "Malawi", value: "MW", flag: "🇲🇼" },
  { title: "Malaysia", value: "MY", flag: "🇲🇾" },
  { title: "Maldives", value: "MV", flag: "🇲🇻" },
  { title: "Mali", value: "ML", flag: "🇲🇱" },
  { title: "Malta", value: "MT", flag: "🇲🇹" },
  { title: "Marshall Islands", value: "MH", flag: "🇲🇭" },
  { title: "Mauritania", value: "MR", flag: "🇲🇷" },
  { title: "Mauritius", value: "MU", flag: "🇲🇺" },
  { title: "Mexico", value: "MX", flag: "🇲🇽" },
  { title: "Micronesia", value: "FM", flag: "🇫🇲" },
  { title: "Moldova", value: "MD", flag: "🇲🇩" },
  { title: "Monaco", value: "MC", flag: "🇲🇨" },
  { title: "Mongolia", value: "MN", flag: "🇲🇳" },
  { title: "Montenegro", value: "ME", flag: "🇲🇪" },
  { title: "Morocco", value: "MA", flag: "🇲🇦" },
  { title: "Mozambique", value: "MZ", flag: "🇲🇿" },
  { title: "Myanmar", value: "MM", flag: "🇲🇲" },
  { title: "Namibia", value: "NA", flag: "🇳🇦" },
  { title: "Nauru", value: "NR", flag: "🇳🇷" },
  { title: "Nepal", value: "NP", flag: "🇳🇵" },
  { title: "Netherlands", value: "NL", flag: "🇳🇱" },
  { title: "New Zealand", value: "NZ", flag: "🇳🇿" },
  { title: "Nicaragua", value: "NI", flag: "🇳🇮" },
  { title: "Niger", value: "NE", flag: "🇳🇪" },
  { title: "Nigeria", value: "NG", flag: "🇳🇬" },
  { title: "North Macedonia", value: "MK", flag: "🇲🇰" },
  { title: "Norway", value: "NO", flag: "🇳🇴" },
  { title: "Oman", value: "OM", flag: "🇴🇲" },
  { title: "Pakistan", value: "PK", flag: "🇵🇰" },
  { title: "Palau", value: "PW", flag: "🇵🇼" },
  { title: "Palestine", value: "PS", flag: "🇵🇸" },
  { title: "Panama", value: "PA", flag: "🇵🇦" },
  { title: "Papua New Guinea", value: "PG", flag: "🇵🇬" },
  { title: "Paraguay", value: "PY", flag: "🇵🇾" },
  { title: "Peru", value: "PE", flag: "🇵🇪" },
  { title: "Philippines", value: "PH", flag: "🇵🇭" },
  { title: "Poland", value: "PL", flag: "🇵🇱" },
  { title: "Portugal", value: "PT", flag: "🇵🇹" },
  { title: "Qatar", value: "QA", flag: "🇶🇦" },
  { title: "Romania", value: "RO", flag: "🇷🇴" },
  { title: "Russia", value: "RU", flag: "🇷🇺" },
  { title: "Rwanda", value: "RW", flag: "🇷🇼" },
  { title: "Saint Kitts and Nevis", value: "KN", flag: "🇰🇳" },
  { title: "Saint Lucia", value: "LC", flag: "🇱🇨" },
  { title: "Saint Vincent and the Grenadines", value: "VC", flag: "🇻🇨" },
  { title: "Samoa", value: "WS", flag: "🇼🇸" },
  { title: "San Marino", value: "SM", flag: "🇸🇲" },
  { title: "Sao Tome and Principe", value: "ST", flag: "🇸🇹" },
  { title: "Saudi Arabia", value: "SA", flag: "🇸🇦" },
  { title: "Senegal", value: "SN", flag: "🇸🇳" },
  { title: "Serbia", value: "RS", flag: "🇷🇸" },
  { title: "Seychelles", value: "SC", flag: "🇸🇨" },
  { title: "Sierra Leone", value: "SL", flag: "🇸🇱" },
  { title: "Singapore", value: "SG", flag: "🇸🇬" },
  { title: "Slovakia", value: "SK", flag: "🇸🇰" },
  { title: "Slovenia", value: "SI", flag: "🇸🇮" },
  { title: "Solomon Islands", value: "SB", flag: "🇸🇧" },
  { title: "Somalia", value: "SO", flag: "🇸🇴" },
  { title: "South Africa", value: "ZA", flag: "🇿🇦" },
  { title: "South Sudan", value: "SS", flag: "🇸🇸" },
  { title: "Spain", value: "ES", flag: "🇪🇸" },
  { title: "Sri Lanka", value: "LK", flag: "🇱🇰" },
  { title: "Sudan", value: "SD", flag: "🇸🇩" },
  { title: "Suriname", value: "SR", flag: "🇸🇷" },
  { title: "Sweden", value: "SE", flag: "🇸🇪" },
  { title: "Switzerland", value: "CH", flag: "🇨🇭" },
  { title: "Syria", value: "SY", flag: "🇸🇾" },
  { title: "Taiwan", value: "TW", flag: "🇹🇼" },
  { title: "Tajikistan", value: "TJ", flag: "🇹🇯" },
  { title: "Tanzania", value: "TZ", flag: "🇹🇿" },
  { title: "Thailand", value: "TH", flag: "🇹🇭" },
  { title: "Togo", value: "TG", flag: "🇹🇬" },
  { title: "Tonga", value: "TO", flag: "🇹🇴" },
  { title: "Trinidad and Tobago", value: "TT", flag: "🇹🇹" },
  { title: "Tunisia", value: "TN", flag: "🇹🇳" },
  { title: "Turkey", value: "TR", flag: "🇹🇷" },
  { title: "Turkmenistan", value: "TM", flag: "🇹🇲" },
  { title: "Tuvalu", value: "TV", flag: "🇹🇻" },
  { title: "Uganda", value: "UG", flag: "🇺🇬" },
  { title: "Ukraine", value: "UA", flag: "🇺🇦" },
  { title: "United Arab Emirates", value: "AE", flag: "🇦🇪" },
  { title: "United Kingdom", value: "GB", flag: "🇬🇧" },
  { title: "United States", value: "US", flag: "🇺🇸" },
  { title: "Uruguay", value: "UY", flag: "🇺🇾" },
  { title: "Uzbekistan", value: "UZ", flag: "🇺🇿" },
  { title: "Vanuatu", value: "VU", flag: "🇻🇺" },
  { title: "Vatican City", value: "VA", flag: "🇻🇦" },
  { title: "Venezuela", value: "VE", flag: "🇻🇪" },
  { title: "Vietnam", value: "VN", flag: "🇻🇳" },
  { title: "Yemen", value: "YE", flag: "🇾🇪" },
  { title: "Zambia", value: "ZM", flag: "🇿🇲" },
  { title: "Zimbabwe", value: "ZW", flag: "🇿🇼" },
];
